#cloud-config
write_files:
- content: |
    server {
        listen 8080;
        server_name demo;

        location / {
            proxy_pass http://127.0.0.1:8000/;
        }
    }
  path: /etc/nginx/conf.d/01_httpbin.conf

