#cloud-config
write_files:
- content: |
    server {
        listen 8080;
        server_name demo;

        location / {
            proxy_pass http://127.0.0.1:8000/;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
  path: /etc/nginx/conf.d/01_httpbin.conf
